version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
        MYSQL_DATABASE: sample_db
        MYSQL_ROOT_PASSWORD: root
    ports:
        - "3306:3306"
    volumes:
        - ./docker/mysql/conf.d:/etc/mysql/conf.d
        - ./docker/mysql/data:/var/lib/mysql
        - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d